# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: swift

sudo: required

env:
  global:
    - WORKSPACE=Example/FRadioPlayer.xcworkspace
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=12.1"
      SCHEME=FRadioPlayer-Example
      SDK=iphonesimulator12.1
    - DESTINATION="platform=OS X,arch=x86_64"
      SCHEME=FRadioPlayer_mac
      SDK=macosx10.14
    - DESTINATION="platform=tvOS Simulator,name=Apple TV,OS=12.1"
      SCHEME=FRadioPlayer_tvOS
      SDK=appletvsimulator12.1
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c
- pod lib lint
