name: FRadioPlayer
options:
  bundleIdPrefix: com.fethica
  deploymentTarget:
    iOS: 10.0
    macOS: 10.12
    tvOS: 10.0
targets:
  FRadioPlayer:
    type: framework
    platform: [iOS]
    sources: Source
    scheme: {}
    settings:
      INFOPLIST_FILE: CarthageInfo.plist
  FRadioPlayer_mac:
    type: framework
    platform: [macOS]
    sources: Source
    scheme: {}
    settings:
      INFOPLIST_FILE: CarthageInfo.plist
  FRadioPlayer_tvOS:
    type: framework
    platform: [tvOS]
    sources: Source
    scheme: {}
    settings:
      INFOPLIST_FILE: CarthageInfo.plist
