name: FRadioPlayer
options:
  bundleIdPrefix: com.fethica
  deploymentTarget:
    iOS: 10.0
    macOS: 10.12
targets:
  FRadioPlayer:
    type: framework
    platform: [iOS, macOS]
    sources: Source
    scheme: {}
    settings:
      INFOPLIST_FILE: CarthageInfo.plist
